general:
  buildTool: "npm"

steps:
  mtaBuild:
    applicationName: "execute-test-cases"
    platform: "CF"

  karmaExecuteTests:
    runCommand: "npm run test:client"
    installCommand: "echo skipping install"
    sidecarImage: "selenium/standalone-chrome:3.141.59"
    sidecarName: "selenium"
    verbose: true

  sonarExecuteScan:
    serverUrl: "https://sonar-dev.releaseowl.com"
    instance: ""
    projectKey: "execute-test-cases"
    token: "ce4412122d0873794f82ff0aec9a3d969d2fa467"
    waitForQualityGate: false
    dockerImage: "sonarsource/sonar-scanner-cli:4.8"
    options:
      - "-Dsonar.projectName=Piper Karma Tests"
      - "-Dsonar.projectVersion=1.0"
      - "-Dsonar.sources=client,lib"
      - "-Dsonar.tests=test/client"
      - "-Dsonar.test.inclusions=test/client/**/*.spec.js"
      - "-Dsonar.exclusions=node_modules/**/*,dist/**/*,gen/**/*,reports/**/*"
      - "-Dsonar.javascript.file.suffixes=.js"
      - "-Dsonar.login=ce4412122d0873794f82ff0aec9a3d969d2fa467"
      //- "-Dsonar.testExecutionReportPaths=reports/TESTS-karma.xml"
      - "-Dsonar.junit.reportPaths=reports"

  testsPublishResults:
    failOnError: false
    junit:
      pattern: "**/reports/TESTS*.xml"
      archive: true
      allowEmptyResults: true