general:
  buildTool: "npm"

steps:
  mtaBuild:
    applicationName: "execute-test-cases"
    platform: "CF"

  karmaExecuteTests:
    runCommand: "npm run test:client"
    installCommand: "echo skipping install"
    sidecarImage: "selenium/standalone-chrome:3.141.59"
    sidecarName: "selenium"
    verbose: true

  sonarExecuteScan:
    serverUrl: "http://54.144.105.219:9000"
    instance: ""
    projectKey: "execute-test-cases"
    token: "squ_79729918fc50c1b6031ee56a075dc51b247406ce"
    waitForQualityGate: false
    dockerImage: "sonarsource/sonar-scanner-cli:latest"
    options:
      - "-Dsonar.projectName=Piper Karma Tests"
      - "-Dsonar.projectVersion=1.0"
      - "-Dsonar.sources=client,lib,test/client"
      - "-Dsonar.tests=test/client"
      - "-Dsonar.test.inclusions=test/client/**/*.spec.js,test/client/mocks.js"
      - "-Dsonar.exclusions=node_modules/**/*,dist/**/*,gen/**/*,lib/config.js"
      - "-Dsonar.javascript.file.suffixes=.js"
      - "-Dsonar.token=squ_79729918fc50c1b6031ee56a075dc51b247406ce"
      - "-Dsonar.javascript.lcov.reportPaths=reports/coverage/lcov.info"
      - "-Dsonar.testExecutionReportPaths=reports/test-execution.xml"

  testsPublishResults:
    failOnError: false
    junit:
      pattern: "**/reports/TESTS*.xml"
      archive: true
      allowEmptyResults: true
    cobertura:
      pattern: "**/reports/coverage/coverage.xml"
      archive: true
      allowEmptyResults: true
      onlyStableBuilds: false