general:
  buildTool: "npm"

steps:
  karmaExecuteTests:
    runCommand: "npm run test:client"
    installCommand: "echo skipping install"
    sidecarImage: "selenium/standalone-chrome:3.141.59"   # ← PIN THIS explicitly
    sidecarName: "selenium"
    verbose: true